### ISSUE TITLE
Why do we need to sqrt(af) to get alleleic frequncy ?

### ISSUE THREAD

**Issue by ahy1221** [sankaranlab/mito-genotyping#1]
I noticed that in the visualize_heatmap_variants.R, the heatmap value which is named as "Allele Frequency" is actually `sqrt(af)`. 
I was wondering that why do we need to do a sqrt operation ?
Isn't that the af matrix is alternative allele frequency ? (alternative allele counts / coverage )

**Comment by caleblareau** [comment]
It's certainly not required, but it is a trick that we figured out a while back to help visualize low frequency variants. By virtue of the sqrt transformation, non-zero effects close to zero become more pronounced relative to higher allele frequencies (noting that the transformation is still one-to-one and thus doesn't affect the relative order of the allele frequencies). Please see that attached image for a depiction of this

**Comment by caleblareau** [comment]
![sqrt_compare](https://user-images.githubusercontent.com/16229089/55084733-d36f5880-507b-11e9-91a4-f46b85b8962d.png)
