### ISSUE TITLE
Summarized Experiment Error/Initial Release Date

### ISSUE THREAD

**Issue by mtvector** [sankaranlab/mito-genotyping#3]
Hi There, great ideas in this code.
Running on R 3.5.1 yields the following error.
`Error in validObject(.Object) : 
  invalid class “SummarizedExperiment” object: 1: 
  nb of rows in 'assay' (4) must equal nb of rows in 'rowData' (49692)
invalid class “SummarizedExperiment” object: 2: 
  nb of cols in 'assay' (14441) must equal nb of rows in 'colData' (1)
Calls: importMito.folder ... new_SummarizedExperiment -> new -> initialize -> initialize -> validObject`
I'm assuming it's due to some version issues in dependencies, have you had to overcome this issue?

I'm more wondering when the approximate release date of your full package will be, or if you have a dev version available, so I know if I can afford to wait for it!
Thanks!
m

**Comment by caleblareau** [comment]
Hi @mtvector -- 

I don't have much of an idea; I've never seen this error before. Is there vey little mitochondria in your cells?

The full pipeline is still a couple of months away but we are working diligently on it :)
