### ISSUE TITLE
RDS file for call_DNA_RNA_variants.R

### ISSUE THREAD

**Issue by esh81** [sankaranlab/mito-genotyping#4]
Hi, 

I want to try the call_DNA_RNA_variants.R script on the RDS file that I generated through the 03_makeRDS.R script, but am having trouble because of the column numbers, etc not matching. Could you post the input /mito_data/atac_rna/pop3_ATAC-RNA.rds file so I can appropriately modify the call_DNA_RNA_variants.R script to run on my data? 

Thank you!

**Comment by caleblareau** [comment]
Added in the most recent commit--

https://github.com/sankaranlab/mito-genotyping/commit/972f28dd16749a0625b89e8362a2e1b3343d7f6c
