### ISSUE TITLE
Cannot open file '00_distance.R': No such file or directory

### ISSUE THREAD

**Issue by mWekking** [sankaranlab/mito-genotyping#5]
call_TF1_bulkATAC.R used 00_distance.R as a source but I cant find this anywhere? Am I missing something or is this not uploaded?

**Comment by caleblareau** [comment]
Yes apparently it was not uploaded; I've added it to the repo now-- https://github.com/sankaranlab/mito-genotyping/commit/7e96a710415ad1d9cce968dd97c303f623e4293f
